function [indiceMelhorHipotese] = avaliarFinal( tabelaAvaliacao )
    tabelaAvaliacao
    media = table(mean(tabelaAvaliacao.acuracia), ...
            mean(tabelaAvaliacao.fMedidaMedia), ...
            mean(tabelaAvaliacao.precisaoMedia), ...
            mean(tabelaAvaliacao.revocacaoMedia), ...
            'VariableNames', {'acuracia', 'fMedidaMedia', 'precisaoMedia', 'revocacaoMedia'})
    [~,indiceMelhorHipotese] = max(tabelaAvaliacao.fMedidaMedia);
    
end

